model:
  name: scgpt
  pretrained_dir: /path/to/scgpt_checkpoint_dir
  architecture:
    embsize: 128
    nhead: 4
    d_hid: 128
    nlayers: 4
    nlayers_cls: 3
    dropout: 0.2
    pad_token: "<pad>"
    pad_value: 0
    mask_value: -1
    include_zero_gene: false
    max_seq_len: 1200
    input_emb_style: category
    n_input_bins: 51
    cell_emb_style: cls
    use_batch_labels: false
    domain_spec_batchnorm: false
    use_fast_transformer: false
